### PR TITLE
Use cloudpipe/keymaster :key:

### PR DESCRIPTION
**Pull request by smashwilson**
Completely untested so far.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Don't worry, we'll send a squad of review minions to audit your handling of cryptographic bits.

If that won't do, I'll just listen to Missy Elliot while looking over it myself.

**Comment by smashwilson** [comment]
Hah. I mostly meant that I was pushing this up because I was done for the day, and I hadn't even run the `script/genkeys` wrapper at all.

Reviewing my (lack of) OpenSSL-fu is another problem entirely :wink:

**Comment by smashwilson** [comment]
Yup:

```
ashl6947@MMN1F3FD58 ~/code/cloudpipe (keymaster-and-gamekeeper=) $ script/genkeys 
>> creating a random password in /Users/ashl6947/code/cloudpipe/certificates/password.
<< random password created
[>>] Generating a CA certificate.
Generating RSA private key, 2048 bit long modulus
..........................+++
.........................+++
e is 65537 (0x10001)
[<<] CA certificate generated.
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 6: /home/hagrid//signed-keypair: source: not found
/home/hagrid//signed-keypair: 76: /home/hagrid//signed-keypair: generate_keypair: not found
```

:boom:

**Comment by smashwilson** [comment]
And now it works :+1:

**Pull request merged**
