### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by smashwilson**
I'm creating a mechanism to provide pluggable authentication services. Go doesn't allow dynamic linking, so I'm going to call out to another daemon over https with a [custom TLS root CA certificate](http://stackoverflow.com/questions/21562269/golang-how-to-specify-certificate-in-tls-config-for-http-client) (probably using the same CA certificate that the Docker daemon does). I'm outlining the protocol for this [on the wiki](https://github.com/cloudpipe/cloudpipe/wiki/Authentication).

### CODE REVIEW

**Comment by smashwilson** [comment]
I spent today making this fairly complex, with capability reporting for things like creating accounts or generating tokens, but I decided to keep the *auth service <- cloudpipe API* integration as minimal as possible. What I'll probably do is add a cloudpipe API endpoint that redirects to the auth service, so our Javascript frontend can hit that, yank the `Location:` header, and interact with the auth service directly for other functionality.

**Comment by smashwilson** [comment]
I'm borrowing the TLS configuration from [docker itself](https://github.com/docker/docker/blob/532e502e9c37d1caab59f9e8d188f6700b197ebb/docker/docker.go#L80-L118) because that's kind of the lower bound on the strength of our network security, anyway, and it's (presumably) had a lot of eyes on it already. A few references for myself, tomorrow:

 * The [Docker guide](https://docs.docker.com/articles/https/) for using openssl to set up a simple CA certificate and keypairs.
 * [openssl documentation](https://www.openssl.org/docs/apps/openssl.html) for command-line arguments and such.

**Comment by smashwilson** [comment]
I've successfully launched everything from fig, linked it all together with TLS credentials, created a non-admin account, generated an API key and submitted a job using those credentials. Looks like we're on :grinning:

**Comment by rgbkrk** [comment]
Wow. :rocket:

**Pull request merged**
